HW2\_JW3597
================

### Problem 1:

``` r
getwd()
```

    ## [1] "/Users/jessiewong/Desktop/DS_Homework2/P8105_HW2_JW3597/HW2_JW3597"

``` r
# Read the csv for problem 1
nyc_transit = read_csv(file = "./data_files/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")
```

    ## Parsed with column specification:
    ## cols(
    ##   .default = col_character(),
    ##   `Station Latitude` = col_double(),
    ##   `Station Longitude` = col_double(),
    ##   Route8 = col_integer(),
    ##   Route9 = col_integer(),
    ##   Route10 = col_integer(),
    ##   Route11 = col_integer(),
    ##   ADA = col_logical(),
    ##   `Free Crossover` = col_logical(),
    ##   `Entrance Latitude` = col_double(),
    ##   `Entrance Longitude` = col_double()
    ## )

    ## See spec(...) for full column specifications.

``` r
# Cleaning the variable names after import: The variable names were changed to lower snake case
nyc_transit = janitor::clean_names(nyc_transit)
names(nyc_transit)  
```

    ##  [1] "division"           "line"               "station_name"      
    ##  [4] "station_latitude"   "station_longitude"  "route1"            
    ##  [7] "route2"             "route3"             "route4"            
    ## [10] "route5"             "route6"             "route7"            
    ## [13] "route8"             "route9"             "route10"           
    ## [16] "route11"            "entrance_type"      "entry"             
    ## [19] "exit_only"          "vending"            "staffing"          
    ## [22] "staff_hours"        "ada"                "ada_notes"         
    ## [25] "free_crossover"     "north_south_street" "east_west_street"  
    ## [28] "corner"             "entrance_latitude"  "entrance_longitude"
    ## [31] "station_location"   "entrance_location"

``` r
select(nyc_transit, line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance_type, ada)
```

    ## # A tibble: 1,868 x 19
    ##    line  station_name station_latitude station_longitu… route1 route2
    ##    <chr> <chr>                   <dbl>            <dbl> <chr>  <chr> 
    ##  1 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  2 4 Av… 25th St                  40.7            -74.0 R      <NA>  
    ##  3 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  4 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  5 4 Av… 36th St                  40.7            -74.0 N      R     
    ##  6 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  7 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  8 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ##  9 4 Av… 45th St                  40.6            -74.0 R      <NA>  
    ## 10 4 Av… 53rd St                  40.6            -74.0 R      <NA>  
    ## # ... with 1,858 more rows, and 13 more variables: route3 <chr>,
    ## #   route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>, route8 <int>,
    ## #   route9 <int>, route10 <int>, route11 <int>, entry <chr>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

``` r
# Converting entry variable from character to a logical variable 
nyc_transit$entry <- as.logical(recode(nyc_transit$entry, "YES" = "TRUE", "NO" = "FALSE"))

# How many distinct stations are there?
name_line = distinct(nyc_transit, station_name, line)
nrow(name_line)
```

    ## [1] 465

``` r
# How many stations are ADA compliant?
ada_compliant = distinct(nyc_transit, station_name, line, ada)
filter(ada_compliant, ada == "TRUE")
```

    ## # A tibble: 84 x 3
    ##    line            station_name                   ada  
    ##    <chr>           <chr>                          <lgl>
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr       TRUE 
    ##  2 4 Avenue        DeKalb Av                      TRUE 
    ##  3 4 Avenue        Pacific St                     TRUE 
    ##  4 42nd St Shuttle Grand Central                  TRUE 
    ##  5 6 Avenue        34th St                        TRUE 
    ##  6 6 Avenue        47-50th Sts Rockefeller Center TRUE 
    ##  7 6 Avenue        Church Av                      TRUE 
    ##  8 63rd Street     21st St                        TRUE 
    ##  9 63rd Street     Lexington Av                   TRUE 
    ## 10 63rd Street     Roosevelt Island               TRUE 
    ## # ... with 74 more rows

``` r
# What proportion of station extrances/exits without vending allow entrance?
novending_yesentry = filter(nyc_transit, vending == "NO", entry == "TRUE")
nrow(novending_yesentry)/nrow(nyc_transit)*100
```

    ## [1] 3.69379

There are 465 distinct stations. There are 84 stations that are ADA compliant. The proportion of station entrances/exits without vending allow entrace is 3.69%.

### Problem 2:

``` r
# read the Mr. Trash Wheel sheet
library(readxl)
trash_wheel = read_excel("./data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 1, range = "A2:N258")

# Variable names used in the Mr. Trash Wheel Sheet are reasonable

# Omit rows that do not include dumpster-specific data
na.omit(trash_wheel, cols  = "Dumpster")
```

    ## # A tibble: 216 x 14
    ##    Dumpster Month  Year Date                `Weight (tons)`
    ##       <dbl> <chr> <dbl> <dttm>                        <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00            4.31
    ##  2        2 May    2014 2014-05-16 00:00:00            2.74
    ##  3        3 May    2014 2014-05-16 00:00:00            3.45
    ##  4        4 May    2014 2014-05-17 00:00:00            3.1 
    ##  5        5 May    2014 2014-05-17 00:00:00            4.06
    ##  6        6 May    2014 2014-05-20 00:00:00            2.71
    ##  7        7 May    2014 2014-05-21 00:00:00            1.91
    ##  8        8 May    2014 2014-05-28 00:00:00            3.7 
    ##  9        9 June   2014 2014-06-05 00:00:00            2.52
    ## 10       10 June   2014 2014-06-11 00:00:00            3.76
    ## # ... with 206 more rows, and 9 more variables: `Volume (cubic
    ## #   yards)` <dbl>, `Plastic Bottles` <dbl>, Polystyrene <dbl>, `Cigarette
    ## #   Butts` <dbl>, `Glass Bottles` <dbl>, `Grocery Bags` <dbl>, `Chip
    ## #   Bags` <dbl>, `Sports Balls` <dbl>, `Homes Powered*` <dbl>

``` r
# Round number of sports balls to the nearest integer and converts the result to an integer variable
trash_wheel$`Sports Balls Rounded` <- as.integer(trash_wheel$`Sports Balls`)

# Median value of sports balls in a dumpter in 2016
median(trash_wheel$`Sports Balls Rounded`)
```

    ## [1] 15.5

``` r
#Read and clean precipitation data for 2016
library(readxl)
precip2016 = read_excel("./data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5)

# Omit rows without precipitation data for 2016
na.omit(precip2016, cols  = "Total")
```

    ## # A tibble: 13 x 2
    ##    `Precipitation (in)` X__1              
    ##    <chr>                <chr>             
    ##  1 Month                Total             
    ##  2 1                    3.23              
    ##  3 2                    5.32              
    ##  4 3                    2.2400000000000002
    ##  5 4                    1.78              
    ##  6 5                    5.19              
    ##  7 6                    3.2               
    ##  8 7                    6.09              
    ##  9 8                    3.96              
    ## 10 9                    4.53              
    ## 11 10                   0.62              
    ## 12 11                   1.47              
    ## 13 12                   2.3199999999999998

``` r
# Adding a variable year for 2016
precip2016 = mutate(precip2016, Year = "2016")

#Read and clean precipitation data for 2017
library(readxl)
precip2017 = read_excel("./data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4)

# Omit rows without precipitation data for 2017
na.omit(precip2017, cols  = "Total")
```

    ## # A tibble: 13 x 2
    ##    `Precipitation (in)` X__1              
    ##    <chr>                <chr>             
    ##  1 Month                Total             
    ##  2 1                    2.34              
    ##  3 2                    1.46              
    ##  4 3                    3.57              
    ##  5 4                    3.99              
    ##  6 5                    5.64              
    ##  7 6                    1.4               
    ##  8 7                    7.09              
    ##  9 8                    4.4400000000000004
    ## 10 9                    1.95              
    ## 11 10                   0                 
    ## 12 11                   0.11              
    ## 13 12                   0.94

``` r
# Adding a variable year for 2017
precip2017 = mutate(precip2017, Year = "2017")

# Combine datasets and convert month to a character variable
precip2016 <- read_excel("./data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5)
precip2017 <- read_excel("./data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4)

totalprecip <- merge(precip2016, precip2017, all.x = TRUE, all.y = TRUE)
```

The number of observations in both resulting datasets was 12 in each and (24 in total). The key variables included year, precipitation (in inches), and the month that the precipation occurred. The total precipation in 2017 was 32.93. The median number of sports balls in a dumpster in 2016 was 15.5.

``` r
library(p8105.datasets)
data("brfss_smart2010")

# Exclude variables for class, topic, question, sample size, and everything from lower confidence limit to GeoLocation / Format the Data to use appropriate variable names
library(dplyr)
select(brfss_smart2010, Year = Year, State = Locationabbr, County = Locationdesc, Response = Response, Health_Score = Data_value)
```

    ## # A tibble: 134,203 x 5
    ##     Year State County                Response              Health_Score
    ##    <int> <chr> <chr>                 <chr>                        <dbl>
    ##  1  2010 AL    AL - Jefferson County Excellent                     18.9
    ##  2  2010 AL    AL - Jefferson County Very good                     30  
    ##  3  2010 AL    AL - Jefferson County Good                          33.1
    ##  4  2010 AL    AL - Jefferson County Fair                          12.5
    ##  5  2010 AL    AL - Jefferson County Poor                           5.5
    ##  6  2010 AL    AL - Jefferson County Good or Better Health         82  
    ##  7  2010 AL    AL - Jefferson County Fair or Poor Health           18  
    ##  8  2010 AL    AL - Jefferson County Yes                           79.3
    ##  9  2010 AL    AL - Jefferson County No                            20.7
    ## 10  2010 AL    AL - Jefferson County Yes                           74.9
    ## # ... with 134,193 more rows
