
# Homework 2: "HW2_JW3597"
#### Name: Jessie Wong
#### Date: September 28, 2018

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

###Problem 1: 
```{r}
# Read the csv for problem 1
nyc_transit = read_csv(file = "../data_files/NYC_Transit_Subway_Entrance_And_Exit_Data.csv")

# Cleaning the data from the CSV:

# Cleaning the variable names after import: The variable names were changed to lower snake case
nyc_transit = janitor::clean_names(nyc_transit)
names(nyc_transit)
```

```{r}
# Specifying the range of columns to keep: retaining line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance
select(nyc_transit, line, station_name, station_latitude, station_longitude, route1, route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance_type, ada)

# Converting entry variable from character to a logical variable 
nyc_transit$entry <- as.logical(recode(nyc_transit$entry, "YES" = "TRUE", "NO" = "FALSE"))
View(nyc_transit$entry)

# How many distinct stations are there?
name_line = distinct(nyc_transit, station_name, line)
nrow(name_line)
# There are 465 distinct stations.

# How many stations are ADA compliant?
ada_compliant = distinct(nyc_transit, station_name, line, ada)
filter(ada_compliant, ada == "TRUE")
# There are 84 stations that are ADA compliant. 

# What proportion of station extrances/exits without vending allow entrance?
novending = filter(nyc_transit, vending == "NO")
yesentry = filter(nyc_transit, entry == "TRUE")
```

###Problem 2: 
```{r}
# read the Mr. Trash Wheel sheet
library(readxl)
trash_wheel = read_excel("../data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 1, range = "A2:N258")

#Use reasonable variable names

# omit rows that do not include dumpster-specific data
na.omit(trash_wheel, cols  = "Dumpster")

# Round number of sports balls to the nearest integer and converts the result to an integer variable
trash_wheel$`Sports Balls Rounded` <- as.integer(trash_wheel$`Sports Balls`)
```

```{r}
#Read and clean precipitation data for 2016
library(readxl)
precip2016 = read_excel("../data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5)

# Omit rows without precipitation data for 2016
na.omit(precip2016, cols  = "Total")

# Adding a variable year for 2016
precip2016 = mutate(precip2016, Year = "2016")

#Read and clean precipitation data for 2017
library(readxl)
precip2017 = read_excel("../data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4)

# Omit rows without precipitation data for 2017
na.omit(precip2017, cols  = "Total")

# Adding a variable year for 2017
precip2017 = mutate(precip2017, Year = "2017")
View(precip2017)

# Combine datasets and convert month to a character variable
precip2016 = read_excel("../data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 5)
precip2017 = read_excel("../data_files/HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = 4)

totalprecip = merge(precip2016, precip2017)
View(totalprecip)

TotalPrecip <- rbind(precip2016, precip2017)
View(Totalprecip)

(precip2016)
(precip2017)
TotalPrecip = merge(precip2016, precip2017)
TotalPrecip
```

```{r}
install.packages("devtools")
devtools::install_github("p8105/p8105.datasets")
library(p8105.datasets)
data("brfss_smart2010")
View(brfss_smart2010)
brfss_smart2010

# Exclude variables for class, topic, question, sample size, and everything from lower confidence limit to GeoLocation
library(dplyr)
select(brfss_smart2010, 'Year', 'Locationabbr', 'Locationdesc', 'Response', 'Data_value')





rename(brfss_smart2010, 'Locationabbr' = 'State', 'Locationdesc' = 'County', 'Data_value'  = 'Health_Score')
brfss_smart2010
       
       , 'Locationdesc', 'Response', 'Data_value')

# Format the data to use appropriate variable names
select(brfss_smart2010, Year, Locationdesc = County, Response, Data_value = Health_Score)

```

